### ISSUE TITLE
Output documentation to bottom panel but not to context menu

### ISSUE THREAD

**Issue by shagabutdinov** [sourcegraph/sourcegraph-sublime#15]
In context menu documentation looks really weird, so probably it is better to output it to the bottom output panel.

**Comment by samertm** [comment]
I wasn't able to get the documentation to show, I kept getting this error:

Traceback (most recent call last):
  File "/home/samer/.config/sublime-text-3/Packages/sourcegraph-dev/commands.py", line 92, in execute
    documentation.append(self._format_example(definition))
  File "/home/samer/.config/sublime-text-3/Packages/sourcegraph-dev/commands.py", line 129, in _format_example
    result.append(first_line)
AttributeError: 'str' object has no attribute 'append'

**Comment by shagabutdinov** [comment]
Sorry, it was wrong pull request, now I fixed bug and double check that everything works fine.
