### ISSUE TITLE
After install of sublime 3 this is the error I get: 'dict' object has no attribute 'settings' 

### ISSUE THREAD

**Issue by TableMountain** [sourcegraph/sourcegraph-sublime#32]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 162, in on_api_ready
    m.plugin_loaded()
  File "sourcegraph_sublime in /Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package", line 96, in plugin_loaded
  File "sourcegraph_sublime in /Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package", line 61, in load_settings
  File "/Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package/sourcegraph_lib.py", line 96, in find_gopath_from_shell
    return get_gopaths(output)
  File "/Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package/sourcegraph_lib.py", line 82, in get_gopaths
    for gopath in gopath_string.split(os.pathsep):
TypeError: Type str doesn't support the buffer API

** 2016-07-16 11:03:28.811954 **:
GoSublime init r16.07.09-1 (0.001s)
|   install margo: no
|   install state: done
| sublime.version: 3114
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: osx-x64
|            ~bin: ~/Library/Application Support/Sublime Text 3/Packages/User/GoSublime/osx-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_devel+8fd1634.exe (ok)
|          go.exe: /usr/local/opt/go/libexec/bin/go (ok)
|      go.version: devel+8fd1634
|          GOROOT: /usr/local/opt/go/libexec
|          GOPATH: ~/work
|           GOBIN: ~/work/bin/ (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /usr/local/bin/fish
|       shell.cmd: ['/usr/local/bin/fish', '-l', '-c', '${CMD}']
--------------------------------

Emmet: No need to update PyV8
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "sourcegraph_sublime in /Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package", line 132, in on_selection_modified_async
AttributeError: 'dict' object has no attribute 'settings'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 320, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "sourcegraph_sublime in /Users/timothybone/Library/Application Support/Sublime Text 3/Installed Packages/Sourcegraph.sublime-package", line 132, in on_selection_modified_async
AttributeError: 'dict' object has no attribute 'settings'
Package Control: Skipping automatic upgrade, last run at 2016-07-16 10:17:19, next run at 2016-07-16 11:17:19 or after

**Comment by rohanpai** [comment]
Hey, Sourcegraph developer here. Thanks for filing the issue. 

Looking into your problem, will get back to you soon with a fix.
